### ISSUE TITLE
Doc link unreacheable

### ISSUE THREAD

**Issue by morucci** [softwarefactory-project/sf-operator#3]
From the doc, this link is not accessible: 
'''
You can check the [CRD’s OpenAPI schema](https://softwarefactory-project.github.io/sf-operator/deployment/config/crd/bases/sf.softwarefactory-project.io_softwarefactories.yaml) for specification details.
'''

**Comment by mhuin** [comment]
Good catch.
There's a quick fix and a time-consuming fix:

* the quick fix would be to link to the schema hosted on github
* the time consuming fix would be to implement the CRD doc generation, using tooling similar to what cert-manager.io does

I'll propose a quick fix today.
